services:
  db:
    container_name: mdb_db
    image: postgres:14.2-alpine
    restart: unless-stopped
    env_file:
      - ./.env/db.env
    volumes:
      - mdb_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mdb_app
    command: gunicorn mdb.wsgi:application -c gunicorn.conf.py
    restart: unless-stopped
    volumes:
      - mdb_static:/usr/src/app/static
      - mdb_media:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env/prod.env
      - ./.env/db.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: mdb_nginx
    restart: always
    ports:
      - 5000:80
    volumes:
      - mdb_static:/usr/src/app/static
      - mdb_media:/usr/src/app/media
    depends_on:
      - web

volumes:
  mdb_static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${STATIC_PATH}'
  mdb_media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${MEDIA_PATH}'
  mdb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_PATH}'
