# Generated by Django 3.2.5 on 2024-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated')),
                ('database', models.CharField(help_text='Alias of the database where the task is saved', max_length=100)),
                ('name', models.CharField(help_text='Name of the task', max_length=255)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('current', models.PositiveIntegerField(default=0, help_text='Current iteration of the task')),
                ('total', models.PositiveIntegerField(help_text='Total iterations of the task')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('REVOKED', 'Revoked'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the task', max_length=20)),
                ('type', models.CharField(choices=[('GENERIC', 'Generic'), ('DB_IMPORT', 'Database Import'), ('DB_UPDATE', 'Database Update'), ('DB_EXPORT', 'Database Export'), ('DB_WORKFLOW', 'Database Workflow')], default='GENERIC', help_text='Type of the task', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
