# Generated by Django 3.2.5 on 2024-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
