# Generated by Django 3.2.5 on 2024-11-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='triggered_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the task was triggered', null=True),
        ),
    ]
