# Generated by Django 3.2.5 on 2024-12-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_task_triggered_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['triggered_on'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
