# Generated by Django 3.2.5 on 2024-12-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('DB_IMPORT', 'Database Import'), ('DB_UPDATE', 'Database Update'), ('DB_EXPORT', 'Database Export'), ('DB_PROCESS', 'Database Process')], default='GENERIC', help_text='Type of the task', max_length=30),
        ),
    ]
